Added 3 nodes of 2 users
w3f/1k-validators-be pull request #2751
Opened 2024-03-15 10:01 UTC by kubaw3f

Added:
- @snail773:matrix.org 2 nodes of the user,
- @themarcus:matrix.org 1 node of the user

2024-03-15 10:01 UTC, kubaw3f commented
@ironoa Element handles of the users were verified

2024-03-18 13:10 UTC, ironoa requested changes

2024-03-18 13:10 UTC, ironoa commented on candidates/kusama.json
> +      "slotId": 847,
@kubaw3f Good Karma is [already present](https://github.com/w3f/1k-validators-be/blob/master/candidates/kusama.json#L817), was that a mistake ?

2024-03-20 08:01 UTC, kubaw3f reviewed
@ironoa @themarcus:matrix.org KYC info updated

2024-03-20 08:16 UTC, merged